version: '3.7'
services:
  mailpit:
    image: axllent/mailpit:v1.7.0
    ports:
      - "8025:8025"
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp_starter
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
    ports:
      - "9000:80"
  wordpress:
    image: wordpress:6.2.0-apache
    ports:
      - "8001:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wp_starter
    volumes:
      - ./data/wp-content:/var/www/html/wp-content
      - ./theme:/var/www/html/wp-content/themes/wp-starter