version: '3.7'
services:
  nginx:
    image: nginx:1.25.1
    depends_on:
      - mailpit
      - phpmyadmin
      - wordpress
    ports:
      - "8000:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
  mailpit:
    image: axllent/mailpit:v1.7.0
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp_starter
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql
      PMA_ABSOLUTE_URI: http://localhost:8000/phpmyadmin/
  wordpress:
    image: wordpress:6.3.1-apache
    depends_on:
      - mysql
    environment:
      WORDPRESS_LOCALE: en_US
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wp_starter
      WORDPRESS_WP_DEBUG: 0
    volumes:
      - wp_data:/var/www/html
      - ./src:/var/www/html/wp-content/themes/wp-starter
      - ./wp-starter-plugin:/var/www/html/wp-content/plugins/wp-starter-plugin
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  # https://stackoverflow.com/questions/50999848/how-to-run-wp-cli-in-docker-compose-yml
  wordpress-cli:
    depends_on:
      - mysql
      - wordpress
    image: wordpress:cli
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wp_starter
    user: root
    restart: on-failure
    command: >
      /bin/sh -c '
      chown -R www-data:www-data /var/www/html/wp-content/uploads;
      sleep 10;
      php /wp-init/wp-init.php
      '
    volumes:
      - wp_data:/var/www/html
      - ./src:/var/www/html/wp-content/themes/wp-starter
      - ./wp-starter-plugin:/var/www/html/wp-content/plugins/wp-starter-plugin
      - ./wp-init:/wp-init
      - cli_data:/etc/clidata
      - ./restore:/etc/wp-starter/restore
volumes:
  db_data:
  wp_data:
  cli_data: