version: '3.7'
services:
  nginx:
    image: nginx:1.25.1
    depends_on:
      - mailpit
      - phpmyadmin
      - wordpress
    ports:
      - "8000:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
  mailpit:
    image: axllent/mailpit:v1.7.0
  mariadb:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp_starter
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  mysql-import:
    image: mysql:8
    depends_on:
      - mariadb
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp_starter
    command: >
      /bin/sh -c '
      chmod +x ./wp-init/import-db.sh && ./wp-init/import-db.sh
      '
    volumes:
      - db_data:/var/lib/mysql
      - ./wp-init:/wp-init
      - ./restore:/etc/wp-starter/restore
      - cli_data:/etc/clidata
  phpmyadmin:
    image: phpmyadmin:5
    depends_on:
      - mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mariadb
      PMA_ABSOLUTE_URI: http://localhost:8000/phpmyadmin/
  wordpress:
    image: wordpress:6.3.1-apache
    depends_on:
      - mariadb
    environment:
      WORDPRESS_LOCALE: en_US
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wp_starter
      WORDPRESS_WP_DEBUG: 0
    volumes:
      - wp_data:/var/www/html
      - ./src:/var/www/html/wp-content/themes/wp-starter
      - ./wp-starter-plugin:/var/www/html/wp-content/plugins/wp-starter-plugin
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  # https://stackoverflow.com/questions/50999848/how-to-run-wp-cli-in-docker-compose-yml
  wordpress-cli:
    depends_on:
      - mariadb
      - wordpress
    image: wordpress:cli
    environment:
      SITE_ROOT_URL: http://localhost:8000
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wp_starter
      ADMIN_USERNAME: user
      ADMIN_PASSWORD: pass
      ADMIN_EMAIL: info@ducode.org
    user: root
    restart: on-failure
    command: >
      /bin/sh -c '
      set -eu;
      if [ -d "/var/www/html/wp-content/uploads" ]; then chown -R www-data:www-data /var/www/html/wp-content/uploads; fi;
      sleep 10;
      php /wp-init/wp-init.php
      '
    volumes:
      - wp_data:/var/www/html
      - ./src:/var/www/html/wp-content/themes/wp-starter
      - ./wp-starter-plugin:/var/www/html/wp-content/plugins/wp-starter-plugin
      - ./wp-init:/wp-init
      - cli_data:/etc/clidata
      - ./restore:/etc/wp-starter/restore
volumes:
  db_data:
  wp_data:
  cli_data: